### ISSUE TITLE
Fix broken UI input fields for Loki queries in Grafana on Chrome

### ISSUE THREAD

**Issue by yondonfu** [livepeer/livepeer-monitoring#18]
Sometimes when I try typing a Loki query, the cursor jumps around and when I run the query I get the following error:

<img width="732" alt="Screen Shot 2022-10-18 at 11 47 16 AM" src="https://user-images.githubusercontent.com/5933273/196479799-14eb3f0b-06f2-45ff-97eb-f2b8530d6cd4.png">

There are no problems when I use Grafana in Safari.

Based on https://github.com/grafana/grafana/issues/54535 looks like this might've been fixed in a more recent version of Grafana.

**Comment by exilehanharr** [comment]
Detected the same issue in Chrome-based browsers on grafana 9.2.0. Grafana 9.1.4 doesn't contain this issue.

**Comment by hjpotter92** [comment]
Fixed by bumping grafana to v9.3.1
